### ISSUE TITLE
No tt util after pip install

### ISSUE THREAD

**Issue by cavejay** [dribnif/tt#1]
I think this problem is because I have little experience with pip installs, but how do I run the util once it's been installed with pip?

tt and tt-time-tracker both don't exist on my path after the pip install.

**Comment by dribnif** [comment]
Oh, looks like a bug. I'll reproduce it asap and get back to you.

**Comment by dribnif** [comment]
Try uninstalling 
`python3 -m pip uninstall tt-time-tracker`

and reinstalling with the verbose flag set, and check where it gets installed. I tried this on a Mac and there pip explicitly told me, that the 

`python3 -m pip install --user --verbose tt-time-tracker`

and check where it gets installed. It can very well be that the new binary is just not in your $PATH

**Comment by cavejay** [comment]
it installed to .local/bin/tt which wasn't in fish's default path. Thanks for the guidance
