### ISSUE TITLE
Missing -h or --help arg

### ISSUE THREAD

**Issue by cavejay** [dribnif/tt#2]
Currently it appears the only source of how to use tt is the readme.md.

It is a standard for CLI tools to support some sort of -h or --help switch that provides an overview of the arguments expected.

**Comment by dribnif** [comment]
You are absolutely right. Will get right on it. :)

**Comment by dribnif** [comment]
just released version 1.0.2. 
Upgrade to it with:

`python3 -m pip install --user --upgrade tt-time-tracker`

Please let me know if there is anything I've missed.
Otherwise feel free to close the issue :)

**Comment by dribnif** [comment]
Didn't realise, merging a pullrequest would close the issue automatically
